### ISSUE TITLE
[Android Bootcamp] Project 0: Todo - Ready for Review

### ISSUE THREAD

**Issue by danielhochman** [danielhochman/codepath-todo#2]
My app is complete!  Please review. /cc @codepathreview @codepath

Also I have a [pull request #1](https://github.com/danielhochman/codepath-todo/pull/1) open which persists items to [Couchbase Lite](https://github.com/couchbase/couchbase-lite-android/) and uses a custom adapter to display the `Document` objects from Couchbase properly. The only outstanding bug that I need to fix is item ordering when read from the database `onCreate()`. After I fix that I plan on using that PR as a basis for additional improvements such as item styling and additional fields (completed, date added, date due). I would appreciate a review on it as well. I made several guesses as to where to place logic to properly handle the new persistence layer.

Looking forward to talking on the phone with someone from the program soon!

Daniel

**Comment by nesquena** [comment]
Daniel,

Looks good! This was intended in part to give you an introduction to the general rhythm of this course. The course is entirely project based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical Android development and best practices as quickly as possible. We also do a personalized code review for each submitted project once the bootcamp starts.

The next step is to continue working on [extensions to your todo app](http://courses.codepath.com/snippets/intro_to_android/prework#heading-5-extending-your-todo) and to **schedule a short 5-10 minute phone conversation** [here](https://www.google.com/calendar/selfsched?sstoken=UURvT01vbzBza1pnfGRlZmF1bHR8NzVjYzBkN2EyZTRiOGRmYjZlZjhmMjA2N2IyMGMwYWU). Navigate to [February 10th and dates onward](https://www.google.com/calendar/selfsched?sstoken=UURvT01vbzBza1pnfGRlZmF1bHR8NzVjYzBkN2EyZTRiOGRmYjZlZjhmMjA2N2IyMGMwYWU) and choose a 15-minute slot. Let us know if none of those times work.

Please make sure to **include the best number** to reach you at in the scheduled event? Look forward to chatting soon!

**Comment by nesquena** [comment]
> Also I have a pull request #1 open which persists items to Couchbase Lite and uses a custom adapter to display the Document objects from Couchbase properly. The only outstanding bug that I need to fix is item ordering when read from the database onCreate(). After I fix that I plan on using that PR as a basis for additional improvements such as item styling and additional fields (completed, date added, date due). I would appreciate a review on it as well. I made several guesses as to where to place logic to properly handle the new persistence layer.

Sounds great, these extensions and optionals can be a great introductory learning exercise. In terms of where to place persistence, and many of the other aspects you mentioned, we will be covering these issues in detail over the course of the bootcamp (best practices, antipatterns, etc). For now just focus on playing around as much as you can as you mentioned (UI, custom list views, adding multiple attributes to the Todo item). Nice job on the custom array adapter and couch base integration.
